"""Add listings and price history

Revision ID: de921ed4eee1
Revises: 
Create Date: 2020-10-07 18:09:37.884624

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'de921ed4eee1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('room_number', sa.Integer(), nullable=True),
                    sa.Column('area', sa.Integer(), nullable=True),
                    sa.Column('district', sa.Integer(), nullable=True),
                    sa.Column('first_scraping_date', sa.Date(), nullable=True),
                    sa.Column('last_seen_date', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('price_history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('seen_date', sa.Date(), nullable=True),
                    sa.Column('listing_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('listing')
    # ### end Alembic commands ###
